### ISSUE TITLE
Way to retrieve the memory delta, peak and usage

### ISSUE THREAD

**Issue by FrancescAlted** [ianozsvald/ipython_memory_usage#3]
It would be nice to retrieve the memory delta, peak and usage values after executing a command in IPython.  After looking at the code, it seems that these are measured inside a thread, making accessing them a bit difficult.

**Comment by FrancescAlted** [comment]
I have finally implemented this feature, but the way that I figured out required an object oriented interface, and that was a big departure from the original code, so I ended doing my own package for that: https://github.com/FrancescAlted/ipython_memwatcher

In the future it would be nice to fusion both projects, but I have a pressing need now for this.

**Comment by ianozsvald** [comment]
Sorry to be slow! I've linked to your repo from my README. I'm not using this stuff at the moment so it is a low priority for me, maybe we can merge it at an upcoming conference? EuroSciPy, PyConUK, BudapestBIForum?

**Comment by FrancescAlted** [comment]
Yeah, it would be nice to have a quick code sprint for that, but my only conference for the remaining of the year is going to EuroPython, so no luck.  Anyway, let's keep this in mind.  Thanks again for an useful package!
